config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :users
  resources :articles
  get 'static_pages/index'
  get 'static_pages/contact'
  get 'static_pages/about'
  get 'static_pages/blog'
  get 'tags/:tag', to: 'articles#index', as: :tag
  post 'static_pages/thank_you'
  root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      cannot :manage, User
      can :manage, User, :id => user.id
      cannot :index, User
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	acts_as_taggable_on :tags
	is_impressionable counter_cache: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # before_filter :authenticate_user! 
  load_and_authorize_resource

  impressionist :actions=>[:show]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    elsif params[:q]
      search_term = params[:q]
      if Rails.env.development?
        @articles = Article.where("body LIKE ?", "%#{search_term}%") \
        | Article.tagged_with("%#{params[:q]}%")
      else
        @articles = Article.where("body ilike ?", "%#{search_term}%") \
        | Article.tagged_with("%#{params[:q]}%")
      end
    else
      @articles = Article.all.order(date: :desc)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :category, :date, :sampletext, :tag_list, :impressions_count)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	@most_viewed = Article.order('impressions_count DESC').take(5)
  	if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all.order(date: :desc)
    end
  end

  def thank_you
  @name = params[:name]
  @email = params[:email]
  @message = params[:message]
  ActionMailer::Base.mail(from: @email,
      to: 'szabogergely07@gmail.com',
      subject: "A new contact form message from #{@name}",
      body: @message).deliver_now
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! 
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :sampletext %>
    <%= f.text_field :sampletext %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class='field'>
    <%= f.label :tag_list, 'Tags (separated by commas)' %><br/>
    <%= f.text_field :tag_list %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_tag_form.html.erb
 <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4 sidebar">


                <!-- Blog Search Well -->
                <div class="well">
                  <h4>Blog Search</h4>
                  <div class="input-group">
                    <%= form_tag("/articles", method: "get", class: "navbar-form", role: "search") do %>
                      <div class="form-group">
                        <%= text_field_tag(:q, nil, placeholder: "Search for an Article", class: "form-control") %>
                      </div>
                      <%= submit_tag("Search", type: "submit", class: "btn btn-default", id: "search-field") %>
                    <% end %>
                  </div>
                  <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li>
                                  <% @articles.each do |article| %>
                                    <%= raw(article.tag_list.map { |t| link_to t, tag_path(t) }.join(' ')) %>
                                  <% end %>

                                </li>
                                
                            </ul>
                        </div>
                        
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
               
                    
                </div>

            </div>

app/views/articles/blog.html.erb
 <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->
                <div class="container">
                    <%= link_to 'Create New Article', new_article_path %>
                </div>

                <% @articles.each do |article| %>

                <!-- Title -->
                <h1><%= article.title %></h1>

                <!-- Author -->
                <p class="lead">
                    by <a href="#">UserName</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on <%= article.date %></p>

                
                <hr>

                <!-- Post Content -->
                <p class="lead"><%= article.body %></p>

                <div class="container">
                    <%= link_to 'Show', article %>
                    <%= link_to 'Edit', edit_article_path(article) %>
                    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>

                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        <!-- Nested Comment -->
                        <div class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object" src="http://placehold.it/64x64" alt="">
                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">Nested Start Bootstrap
                                    <small>August 25, 2014 at 9:30 PM</small>
                                </h4>
                                Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                            </div>
                        </div>
                        <!-- End Nested Comment -->
                    </div>
                </div>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#"><%= article.category %></a>
                                </li>
                                
                            </ul>
                        </div>
                        
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
               
                    
                </div>
                <% end %>
            </div>

        </div>
        <!-- /.row -->

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="content">
  <div class="container">
   
           <ul id="myList">
              <!-- These are our grid blocks -->
              <li>
            <div class="l_g">
             <% @articles.each do |article| %> 
              <div class="col-md-3 praesent">
                <div class="l_g_r">
                  <div class="dapibus">
                    <h2><%= article.title %></h2>
                    <p class="adm">Posted by <a href="#">Admin</a>  |  on <%= article.date %></p>
                    <a href=""><img src="" class="img-responsive" alt=""></a>
                    <p><%= article.body.first(200) %>(...) 
                    </p>
                    <%= link_to 'Read more...', article, class: "link" %>
                   <br>
                    <% if signed_in? && current_user.admin? %>
                    <%= link_to 'Edit', edit_article_path(article) %>
                    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                    
                  </div>
                </div>
              </div>
           <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
           

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsBlog</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }
    </script>


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="banner">
      <div class="container">
        <div class="header">
          <div class="logo">
            <a href="<%= static_pages_index_path %>"> <%= image_tag("newsblog-logo2.jpg", class: "img-responsive logo-pic") %> </a>
          </div>
          <h2 class="greg">by Greg</h2>
        <div class="header-right">
          <ul>
            <li><a href="#"><i class="fb"> </i></a></li>
            <li><a href="#"><i class="twt"> </i></a></li>
            <li>
              <div class="search2">
                <form>
                  
                    <%= form_tag("/articles", method: "get", class: "", role: "search") do %>
                    
                      <%= text_field_tag(:q, nil, placeholder: "Search", class: "") %>
                    
                    <%= submit_tag("", type: "submit", class: "", id: "") %>
                    <% end %>
                 
                </form>
              </div>
            </li>
        <div class="clearfix"></div>
          </ul>
          
      </div>
        <div class="clearfix"> </div>
    </div>
    <div class="head-nav">
      <span class="menu"> </span>
      <ul class="cl-effect-15">
      <li class="active"><%= link_to "HOME", static_pages_index_path, {"data-hover": "HOME"} %></li>
        <li><%= link_to "ABOUT", static_pages_about_path, {"data-hover": "ABOUT"} %></li>
        <li><%= link_to "CONTACT", static_pages_contact_path, {"data-hover": "CONTACT"} %></li>
        <li>
          <% if user_signed_in? %>
          <%= link_to "LOGOUT", destroy_user_session_path, {:method => :delete, "data-hover": "LOGOUT"} %>
          <% else %>
          <%= link_to "LOGIN", new_user_session_path, {"data-hover": "LOGIN"} %>
          <%= link_to "SIGN UP", new_user_registration_path, {"data-hover": "SIGN UP"} %>
          <% end %>    
        </li>
        <li>
          <% if signed_in? && current_user.admin? %>
            <%= link_to "Create New Article", new_article_path, {"data-hover": "Create New Article"} %>
          <% end %>
        </li>
          <div class="clearfix"> </div>
      </ul>
    </div>
  </div>
</div>






 <!-- <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p> -->

    <%= yield %>


  <!-- footer -->
  <div class="footer">
    <div class="container">
      <div class="col-md-3 copy">
        <div class="top1">
          <i class="ham"></i>
        </div>
        <div class="top2">
          <h6>© 2017 Gergely Szabo</h6>
          <p>All rights reserved</p>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="col-md-3 copy">
        <div class="top1">
          <i class="men"></i>
        </div>
        <div class="top2">
          <h6>Template by: </h6>
          <p><a href="http://w3layouts.com/">W3layouts</a></p>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="col-md-3 copy">
        <div class="top1">
          <i class="app"></i>
        </div>
        <div class="top2">
          <h6>My Portfolio </h6>
          <p><a href="gergely-szabo.bitballoon.com">Have a look!</a></p>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="col-md-3 copy">
        <div class="top1">
          <i class="lik"></i>
        </div>
        <div class="top2">
          <h6>GitHub </h6>
          <p><a href="https://github.com/szabogergely07"> szabogergely07</a></p>
        </div>
        <div class="clearfix"> </div>
      </div>
      <div class="clearfix"> </div>
    </div>
  </div>
<!-- footer -->


  </body>
</html>

app/views/static_pages/about.html.erb
<div class="about">
<div class="container">
		<h2>About</h2>		
<div class="biography">
		<div class="biographys">
			<div class="col-md-4 biography-info">
				<%= image_tag("profile_small.jpg", class: "img-responsive profile-pic") %>
			</div>
			<div class="col-md-8 biography-into">
				<h4>Gergely Szabo</h4>
				<p>
					Hi, I am Greg, this is one of my projects I am creating as a web developer. The engine is Ruby on Rails, I am implementing authentication, authorization, tags and comments. You can create new post just to fill out a new blog post form and the rest is done by the application. The page is being coded, not fully functional yet.
				</p>
				<a href="https://gergely-szabo.bitballoon.com" class="link" target="_blank">You should see my portfolio site!</a>
			</div>
					<div class="clearfix"> </div>
	</div>
		
</div>
	</div>
	</div>

app/views/static_pages/index.html.erb
<div class="content">
  <div class="container">
   <div class="load_more">  
           <ul id="myList">
              <!-- These are our grid blocks -->
              <li>
            <div class="l_g">
             <% @articles.take(3).each do |article| %> 
              <div class="col-md-3 praesent">
                <div class="l_g_r">
                  <div class="dapibus">
                    <h2><%= article.title %></h2>
                    <p class="adm">Posted by <a href="#">Admin</a>  |  on <%= article.date %></p>
                    <!-- <p>Views:</p> -->
                    <a href=""><img src="" class="img-responsive" alt=""></a>
                    <p><%= article.body.first(200) %>(...) 
                    </p>
                    <%= link_to 'Read more...', article, class: "link" %>
                   <br>
                    <% if signed_in? && current_user.admin? %>
                    <%= link_to 'Edit', edit_article_path(article) %>
                    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                    
                  </div>
                </div>
              </div>
            <% end %>

            
              <div class="col-md-3 integ">
                <div class="l_g_r">
                  <div class="posts">
                    <h4>Most viewed posts</h4>
                    <% @most_viewed.each do |most| %> 
                    <h6><%= link_to most.title, most %> (<%= most.impressions_count %>)</h6>
                    <% end %>
                  </div>
                  <div class="comments">
                    <h4>Recent Comments</h4>
                    <h6><a href="#">Amada Doe <span>on</span> Hello World!</a></h6>
                    <h6><a href="#">Peter Doe <span>on</span> Photography</a></h6>
                    <h6><a href="#">Steve Roberts <span>on</span> HTML5/CSS3</a></h6>
                    <h6><a href="#">Doe Peter<span>on</span> Photography</a></h6>
                  </div>
                  <div class="archievs">
                    <h4>Archives</h4>
                    <h6><a href="#">October 2013</a></h6>
                    <h6><a href="#">September 2013</a></h6>
                    <h6><a href="#">August 2013</a></h6>
                    <h6><a href="#">July 2013</a></h6>
                  </div>

                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </li>
         
           <!----//--->

           <li>
            <div class="l_g">
             <% @articles[3..5].each do |article| %> 
              <div class="col-md-3 integ">
                <div class="l_g_r">
                  <div class="integer">
                    <h2><%= article.title %></h2>
                    <p class="adm">Posted by <a href="#">Admin</a>  |  on <%= article.date %></p>
                    <a href=""><img src="" class="img-responsive" alt=""></a>
                    <p><%= article.body.first(200) %>(...) 
                    </p>
                    <%= link_to 'Read more...', article, class: "link" %>
                    <br>
                    <% if signed_in? && current_user.admin? %>
                    <%= link_to 'Edit', edit_article_path(article) %>
                    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>





              <div class="col-md-3 integ">
                <div class="l_g_r">
                  <div class="categories">
                    <h4>Categories</h4>
                    <ul class="list-unstyled">
                      <li>
                        <% @articles.each do |article| %>
                          <%= raw(article.tag_list.map { |t| link_to t, tag_path(t) }.join(' ')) %>
                        <% end %>

                      </li>
                                
                    </ul>
                  </div>
                </div>
              </div>
              <div class="clearfix"></div>
            </div>
          </li>
         <!----//--->
           <li>
            <div class="l_g">
               <div class="l_g">
             <% @articles[6..-1].each do |article| %> 
              <div class="col-md-4 praesent">
                <div class="l_g_r">
                  <div class="dapibus">
                    <h2><%= article.title %></h2>
                    <p class="adm">Posted by <a href="#">Admin</a>  |  on <%= article.date %></p>
                    <a href=""><img src="" class="img-responsive" alt=""></a>
                    <p><%= article.body.first(200) %>(...) 
                    </p>
                    <%= link_to 'Read more...', article, class: "link" %>
                    <br>
                    <% if signed_in? && current_user.admin? %>
                    <%= link_to 'Edit', edit_article_path(article) %>
                    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                  </div>
                </div>
              </div>
              <% end %>
              <div class="col-md-3 integ">
                <div class="l_g_r">
                </div>
              </div>
              <div class="clearfix"></div>
              </div>
            </div>
          </li>

            
          <div class="clearfix"></div>
      
               <!----//---> 
        </ul>
          <div id="loadMore">Load more</div>
          <div id="showLess">Show less</div>

          </div>
  </div>
</div>
<!-- content -->  











app/views/static_pages/thank_you.erb
<h2>THANKS</h2>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>